name: Scrape Datos

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
          run_install: true
      - run: |
          node scraping/articlesAs.js
          node scraping/articlesSport.js
          git config user.name davidgasensi
          git add -A
          git commit -m "Update articles"
          git push origin main
        
